services:

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - db

  api:
    image: test/api
    build: 
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URL=mongodb://db:27017/main
    depends_on:
      - db
  
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  